name: dbt Run Daily

on:
  schedule:
    - cron: '0 3 * * *'  # रोज सकाळी 8:30 IST
  workflow_dispatch:

jobs:
  dbt-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-snowflake dbt-core

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "snowflake-dbt-demo:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: ${{ secrets.DBT_ACCOUNT }}
                user: ${{ secrets.DBT_USER }}
                password: ${{ secrets.DBT_PASSWORD }}
                database: ${{ secrets.DBT_DATABASE }}
                warehouse: COMPUTE_WH
                schema: PUBLIC
                role: SYSADMIN
                threads: 2
          " > ~/.dbt/profiles.yml

      - name: Run dbt
        run: |
          dbt deps
          dbt run
          dbt test
